import type { Metadata } from "next";

import "./globals.css";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
 
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<meta property="fc:frame" content="vNext" />
			<meta property="fc:frame:title" content="Base Foot Print" />
			<meta property="fc:frame:image" content="https://your-image-url.jpg" />
			<meta property="fc:frame:button:1" content="Mint BFT" />
			<meta property="fc:frame:button:1:action" content="tx" />
			<meta property="fc:frame:button:1:target" content="/api/mint-frame" />
			<body className={`antialiased`}>{children}</body>
		</html>
	);
}
